# Site settings
title: Peter E. DeWitt
description: 'I am a Ph.D. Biostatistician.'
url: 'dewittpe.github.io'
baseurl: '/'
google_analytics: 'UA-87261307-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Peter DeWitt'
  email: dewittpe@gmail.com
  twitter_username: Statistics4All
  facebook_username:
  github_username:  dewittpe
  linkedin_username:  
  researchgate_username: Peter_DeWitt
  google_scholar: CBv7wlQAAAAJ&hl=en

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
