---
title: "Software"
---

I have developed and published several R packages and tools.

## phoenix

The phoenix [R package](https://cran.r-project.org/package=phoenix) and
[Python module](https://pypi.org/project/phoenix-sepsis/) implement the Phoenix
criteria for pediatric sepsis and septic shock.

- [website](https://cu-dbmi-peds.github.io/phoenix/index.html)
- [R package](https://cran.r-project.org/package=phoenix)
- [Python module](https://pypi.org/project/phoenix-sepsis/)

- Peer reviewed manuscript in JAMIA Open:
  - [phoenix: an R package and Python module for calculating the Phoenix pediatric
  sepsis score and criteria](https://doi.org/10.1093/jamiaopen/ooae066)

## pedbp

Data and utilities for estimating pediatric blood pressure percentiles by sex,
age, and optionally height (stature) as described in [Martin et.al.
(2022)](doi:10.1001/jamanetworkopen.2022.36918). Blood pressure percentiles for
children under one year of age come from [Gemelli et.al.
(1990)](doi:10.1007/BF02171556).  Estimates of blood pressure percentiles for
children at least one year of age are informed by data from the [National Heart,
Lung, and Blood Institute (NHLBI) and the Centers for Disease Control and
Prevention (CDC)](doi:10.1542/peds.2009-2107C) or from [Lo et.al.
(2013)](doi:10.1542/peds.2012-1292).  The flowchart for selecting the informing
data source comes from [Martin et.al. (2022)](doi:10.1542/hpeds.2021-005998).

- [website](https://www.peteredewitt.com/pedbp/)
- [R package](https://cran.r-project.org/package=pedbp)

- Peer reviewed manuscript in JAMA Network Open:
  - [Development of a Pediatric Blood Pressure Percentile Tool for Clinical
  Decision Support](doi:10.1001/jamanetworkopen.2022.36918)


## REDCapExporter

## cpr

## pccc

## qwraps2

## ensr
